"""add enr

Revision ID: 2afbf065de02
Revises: d3672f5ca375
Create Date: 2023-05-02 00:26:31.294630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afbf065de02'
down_revision = 'd3672f5ca375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    op.drop_table('assign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assign',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='assign_activity_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='assign_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'activity_id', name='assign_pkey')
    )
    op.drop_table('enrollment')
    # ### end Alembic commands ###
